### ISSUE TITLE
Задержка после клика на Native Promo / Video рекламе

### ISSUE THREAD

**Issue by ashmaliy** [myTargetSDK/mytarget-ios#10]
Здравствуйте.

В тестовом приложении, при клике на рекламу, происходит задержка 2-5 секунд перед открытием Landing URL.
Т.е. после клика 5 секунд висит алерт с активити индикатором и кнопкой Cancel, и только потом открывается новый скрин с деталями рекламы. При повторном клике на ту же рекламу задержка все-равно есть, но около 1 секунды.
Воспроизводится 100 % для Native Ad -> Promo и Native Ad -> Video.

Также проблема происходит в отдельном проекте (использую MTRGNativeAd), пробовал использовать версию MyTargetSDK 5.6.0 и 5.7.5.

Предполагаю, задержка вызвана загрузкой инфы, которая будет показана на новом скрине?
Возможно, имеет смысл добавить в SDK сеттинг для открытия Landing URL в Safari, а не внутри приложения.

**Comment by aserrr** [comment]
Пока висит алерт мы загружаем SKStoreProductViewController и такая большая задержка может быть связана с медленным соединением между приложением и серверами Apple (или с проблемами на стороне App Store).
URL может также открываться и в приложении App Store (через Safari). Это зависит от настроек рекламного слота.

**Comment by ashmaliy** [comment]
> Это зависит от настроек рекламного слота.

хочу уточнить: данная настройка находится где-то в админке, т.е. это делается не на клиенте?
как называется данный сеттинг?

буду благодарен за ответ.
