### ISSUE TITLE
linking fail myTargetSDK 5.11.2

### ISSUE THREAD

**Issue by AleyRobotics** [myTargetSDK/mytarget-ios#12]
Linker message:

ld: in ......Build/Products/Debug-iphoneos/MyTargetSDK.framework/MyTargetSDK(MTRGViewability.o), building for iOS, but linking in object file built for iOS Simulator, file '......./Build/Products/Debug-iphoneos/MyTargetSDK.framework/MyTargetSDK' for architecture arm64

build with version 5.10.3 success.
build with version 5.11.2 **FAIL**.

**Comment by aserrr** [comment]
Hi Yuri,

We hasn't encountered such issue yet.

Could you please provide us with some additional info:
- Did you tried Xcode -> Product -> Clean Build Folder?
- Do you use CocoaPods or was myTarget SDK installed manually?
- Build environment, especially versions of macOS, Xcode, CocoaPods, M1 or Intel?
- How your app configured in Build Settings -> Architectures?
- If possible, please attach an empty test Xcode project where an issue reproduces.

**Comment by AleyRobotics** [comment]
Clean and delete derived data folder not help. 
Used cocoPods.
Target iOS 13.0.

**Comment by aserrr** [comment]
The information you've provided isn't enough.
We are still unable to reproduce this issue.
Also there are no other similar cases reported.

**Comment by altk** [comment]
Closed due to timeout for response.
