### ISSUE TITLE
SKAdImpression: Undefined symbols for architecture arm64 (MyTargetSDK 5.11.2)

### ISSUE THREAD

**Issue by ashmaliy** [myTargetSDK/mytarget-ios#13]
There is an issue with latest release 5.11.2: the build fails in case project contains "Other Linker Flags": -ObjC .
Happens on device and on Simulator (M1). Does not reproduce with SDK version 5.10.3.
'StoreKit.framework' is linked to the project.

Error description:
`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_SKAdImpression", referenced from:
      objc-class-ref in MyTargetSDK(MTRGCommonBannerParser.o)
ld: symbol(s) not found for architecture arm64`

**Comment by aserrr** [comment]
Which version of Xcode do you use?

**Comment by ashmaliy** [comment]
Xcode 12.4

**Comment by aserrr** [comment]
Well, it doesn't support iOS 14.5+
Please use Xcode 12.5+
We'll add this note to readme in order to avoid further confusion.
