### ISSUE TITLE
Add support for Apple Silicon (M1)

### ISSUE THREAD

**Issue by xoridius** [myTargetSDK/mytarget-ios#16]
Shipped framework breaks iOS Simulator builds on Apple Silicon (M1 macs).

XCFrameworks are required to include the **arm64 slice** for iOS devices and the macOS iOS simulator for Macs running on Apple silicon.

To fix the issue:

1) Recompile libraries as XCFrameworks with `arm64-simulator` slice (`generic/platform=iOS Simulator`)
2) Remove deprecated `EXCLUDED_ARCHS`[1] and `VALID_ARCHS`[2] build configuration overrides from podspecs (remove all uses of `spec.pod_target_xcconfig` and `spec.user_target_xcconfig`).

Simplified example of building framework target as XCFramework:

```zsh
# archive framework for device targets
xcodebuild archive -project 'Project.xcodeproj' -scheme 'FrameworkDemo' -configuration Release -destination 'generic/platform=iOS' -archivePath 'archive/FrameworkDemo-iphoneos.xcarchive' SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES

# archive framework for simulator targets (code signing not required)
xcodebuild archive -project 'Project.xcodeproj' -scheme 'FrameworkDemo' -configuration Release -destination 'generic/platform=iOS Simulator' -archivePath 'archive/FrameworkDemo-iphonesimulator.xcarchive' SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"

# build XCFramework
xcodebuild -create-xcframework \
-framework archive/FrameworkDemo-iphoneos.xcarchive/Products/Library/Frameworks/FrameworkDemo.framework \
-framework archive/FrameworkDemo-iphonesimulator.xcarchive/Products/Library/Frameworks/FrameworkDemo.framework \
-output archive/FrameworkDemo.xcframework
```

References:

- WWDC19 XCFramework announcement https://www.wwdcnotes.com/notes/wwdc19/416/

- Create an XCFramework
https://help.apple.com/xcode/mac/current/#/dev544efab96

- Supporting XCFrameworks by PSPDFKit https://pspdfkit.com/blog/2020/supporting-xcframeworks/, https://pspdfkit.com/blog/2021/advances-in-xcframeworks/

- XCFramework example project 
https://github.com/bielikb/xcframeworks

- Cocoapods podspec examples with binary XCFrameworks: [FirebaseAnalytics](https://github.com/CocoaPods/Specs/blob/master/Specs/e/2/1/FirebaseAnalytics/9.1.0/FirebaseAnalytics.podspec.json) [UnityAds](https://github.com/CocoaPods/Specs/blob/master/Specs/2/e/8/UnityAds/4.2.1/UnityAds.podspec.json) [PSPDFKit](https://github.com/CocoaPods/Specs/blob/master/Specs/c/5/5/PSPDFKit/11.4.0/PSPDFKit.podspec.json) [OneSignal](https://github.com/CocoaPods/Specs/blob/master/Specs/c/1/2/OneSignal/3.11.1/OneSignal.podspec.json) [FBSDKCoreKit](https://github.com/CocoaPods/Specs/blob/master/Specs/9/b/5/FBSDKCoreKit/13.2.0/FBSDKCoreKit.podspec.json)

- TN3117: Resolving architecture build errors on Apple silicon https://developer.apple.com/documentation/technotes/tn3117-resolving-build-errors-for-apple-silicon

    "Only use the `EXCLUDED_ARCHS` build setting on targets where the final released app is not using the target’s functionality on a specific architecture, such as a Mac app that only supports a legacy feature on Intel-based Mac computers ... Do not use `EXCLUDED_ARCHS` with pre-compiled libraries that are not updated with support for the iOS, watchOS, or tvOS simulators on Apple silicon."

- `VALID_ARCHS` flag has been deprecated since Xcode 12 (September 2020)
https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes

-  `VALID_ARCHS` issues
https://github.com/search?q=VALID_ARCHS&type=issues

- Cocoapods docs: "`user_target_xcconfig` attribute is not recommended as Pods should not pollute the build settings of the user project and this can cause conflicts."
https://guides.cocoapods.org/syntax/podspec.html#user_target_xcconfig

**Comment by aserrr** [comment]
Hello,

Thank you for detailed report.

Actually, myTarget SDK already supports Apple Silicon (M1) since v.5.11.0 (released 2021-04-16)

mytarget-ios-sdk-5.15.2/MyTargetSDK.xcframework/ios-arm64_x86_64-simulator/MyTargetSDK.framework
> lipo -archs MyTargetSDK 
arm64 x86_64

mytarget-ios-sdk-5.15.2/MyTargetSDK.xcframework/ios-arm64_armv7/MyTargetSDK.framework
> lipo -archs MyTargetSDK 
arm64 armv7

Also, there is no "user_target_xcconfig" attribute in .podspec file. We use only "pod_target_xcconfig" attribute in order to simplify Pods merging process. Yes, you're right, there is "VALID_ARCHS" parameter used but I believe it should be ignored while installation. Anyway we'll check if it cause some issues and test our SDK installation side by side with others.

**Comment by xoridius** [comment]
@aserrr Thanks for response.

`user_target_xcconfig` is used in `myTrackerSDK` dependency pod, which cause xcconfig merge conflicts during `pod install` and pollutes user target.
Also I believe it is not required to specify `source_files` and `public_header_files` fields for framework headers when using `vendored_frameworks`, so there is a little room for podspec cleanup.

Would you mind sharing details about your case using `pod_target_xcconfig` you mentioned earlier?

**Comment by aserrr** [comment]
We will update podspec files for myTarget and myTracker SDK in future releases.
