### ISSUE TITLE
Бесконечный индикатор загрузки

### ISSUE THREAD

**Issue by imerkulov** [myTargetSDK/mytarget-ios#2]
Если в момент открытия рекламы (нажатия по банеру) пропадает интернет, то модально открытий экран нельзя закрыть по нажатию на кнопку "Cancel", плюс на экране бесконечно крутится индикатор загрузки. Помогает только закрытие приложения.

Подскажите как можно это поправить.

**Comment by aserrr** [comment]
Проверил все возможные варианты. Такое поведение не зависит от наличия интернета и проявляется при попытке перехода в AppStore когда приложение выполняется на симуляторе.
Добавим проверку TARGET_OS_SIMULATOR в следующих релизах.

**Comment by imerkulov** [comment]
[](url)

**Comment by imerkulov** [comment]
Прикладываю гифку 
![xlicxeucdtb3g](https://cloud.githubusercontent.com/assets/1902666/24907438/eeb7d184-1ec4-11e7-96df-cc6c0e5dc25d.gif)

**Comment by imerkulov** [comment]
![mytarget-tastcase-video-2](https://cloud.githubusercontent.com/assets/1902666/24908027/417eccae-1ec7-11e7-82c5-46f17c0cbb9f.gif)

**Comment by aserrr** [comment]
Исправили кнопку Cancel в 4.6.11
