### ISSUE TITLE
Instream ad

### ISSUE THREAD

**Issue by YoungYanchi** [myTargetSDK/mytarget-ios#24]
Доброго времени суток, подскажите пожалуйста. Имеется ли поддержка instream видео рекламы в мобильном приложении?
Если instream поддерживается, где можно ознакомиться? Спасибо!

**Comment by aserrr** [comment]
Здравствуйте,
Да, есть поддержка Instream Video рекламы. Ознакомиться можно вот [тут](https://target.vk.ru/help/partners/mob/ios_formats/ru#ios_instreamvideo).

**Comment by YoungYanchi** [comment]
> Здравствуйте, Да, есть поддержка Instream Video рекламы. Ознакомиться можно вот [тут](https://target.vk.ru/help/partners/mob/ios_formats/ru#ios_instreamvideo).

спасибо
