### ISSUE TITLE
Атрибуты nullable и nonnull 

### ISSUE THREAD

**Issue by imerkulov** [myTargetSDK/mytarget-ios#3]
Добавьте, пожалуйста, атрибуты `nullable` и `nonnull` у свойств объектов.

В Swift SDK собирается с бэнгами, хотя не все свойства required. Хотелось бы нагляднее разделять `nullable` свойства от `nonnull`.

**Comment by aserrr** [comment]
Илья,
Атрибуты добавим в одном из следующих релизов.
Если не сложно, покажите, пожалуйста, как оно собирается с бэнгами.

**Comment by lostillusion** [comment]
Добавлено в 4.6.21
