### ISSUE TITLE
Неправильно обрабатывается прерывание аудио сессии для аудиорекламы, реклама не доигрывает до конца.

### ISSUE THREAD

**Issue by suzhaev** [myTargetSDK/mytarget-ios#4]
[myTargetLogs.txt](https://github.com/myTargetSDK/mytarget-ios/files/1088754/myTargetLogs.txt)

Логи прикрепил.
Как повторить:
1. Получить рекламу
2. Во время проигрывания рекламы получить AVAudioSessionInterruptionNotification (например входящий звонок)
3. "Поговорить" по времени = длине рекламного ролика или больше например при длине рекламы 20 секунд поговорить 21
4. Положить трубку, от sdk приходит событие stop

Логи и все вызовы, которые делает приложение есть в логах

**Comment by aserrr** [comment]
Олег,
Мы уже обсуждали эту ситуацию и я присылал код обработчика AVAudioSessionInterruptionNotification с которым всё работает правильно.

[InstreadAudioLog.txt](https://github.com/myTargetSDK/mytarget-ios/files/1090706/InstreadAudioLog.txt)

**Comment by suzhaev** [comment]
Да, но хочется решить проблему нормально, а не городить костыли с dispatch_after.
По дебагу понятно, что событие stop приходит от sdk по таймеру, т.е когда сессия прерывается таймер продолжает работать. 
Если баг повторяется в вашем тестовом приложении логично предположить, что будет повторяться в любом приложении с myTarget sdk, все будут dispatch_after писать?
Спасибо

**Comment by aserrr** [comment]
Вот код с которым тестировал сегодня:
`				dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{
					[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategorySoloAmbient error:nil];
					[[AVAudioSession sharedInstance] setActive:YES error:nil];
					dispatch_async(dispatch_get_main_queue(), ^{
						[_instreamAudioAd resume];
					});
				});
`

**Comment by suzhaev** [comment]
И все отлично работает? используем абсолютно такой же код

**Comment by aserrr** [comment]
Да. По логу видно же.

**Comment by suzhaev** [comment]
Хорошо, по нашему логу видно, что не работает, могу еще раз скинуть скрин, где видно что приходит событие stop. 
В логах наших правильно делаются все вызовы же?

**Comment by aserrr** [comment]
Про необходимость dispatch_after читал где-то. Это из-за особенностей AVAudioSession, а не нашего SDK.

**Comment by suzhaev** [comment]
@aserrr а как sdk вообще связно с AVAudioSession и причем тут событие stop?

**Comment by aserrr** [comment]
Какое значение приходит в JSON-е для connectionTimeout параметра?

**Comment by suzhaev** [comment]
@aserrr где это можно посмотреть?

**Comment by aserrr** [comment]
Добавил запись событий а debug log, пойдёт в следующий релиз.
