### ISSUE TITLE
Настройка для выставления timeout на запрос рекламы.

### ISSUE THREAD

**Issue by suzhaev** [myTargetSDK/mytarget-ios#5]
Сделать метод для настройки таймаута на запрос аудиорекламы `[instreamAd load]`, если ответ не пришел в течении N секунд, вызывается onErrorWithReason и плеер продолжает проигрывание музыки

Например:
`[customParams setTimeout:@(2.0)];`

**Comment by lostillusion** [comment]
Такую опцию сделаем можем, но минимальное значение будет 5 секунд.

**Comment by suzhaev** [comment]
@lostillusion отлично, спасибо

**Comment by lostillusion** [comment]
добавлено свойство loadingTimeout в 4.6.19
