### ISSUE TITLE
SFSafariViewController crash

### ISSUE THREAD

**Issue by ERussel** [myTargetSDK/mytarget-ios#6]
При попытке sdk открыть нативный рекламный блок (MTRGNativeAd) приложение вылетает:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'The specified URL has an unsupported scheme. Only HTTP and HTTPS URLs are supported.'

Если это поможет, то рекламный блок отображал офер - GodLands.

**Comment by aserrr** [comment]
Какая используется версия myTarget SDK?

**Comment by lostillusion** [comment]
closed (no info)
