### ISSUE TITLE
Не отрабатывает клик, если сразу после клика уйти на другой viewController

### ISSUE THREAD

**Issue by bynoodles** [myTargetSDK/mytarget-ios#8]
Здравствуйте

В тестовом приложении можно воспроизвести с рекламой типа ```MTRGInterstitialAd```.
Если в делегатном методе определить
```
- (void)onClickWithInterstitialAd:(MTRGInterstitialAd *)interstitialAd
{
    [self.navigationController popViewControllerAnimated:YES];
}
```
то после клика не открывается содержимое рекламы, происходит только возврат на предыдущий экран.

**Comment by aserrr** [comment]
Добрый день,
А какое поведение ожидаете в этом случае?
Текущий контроллер закрывается принудительно вместе с экземпляром MTRGInterstitialAd
То есть не существует больше ни самой рекламы, ни контроллера, в котором она была показана.
