### ISSUE TITLE
Attempt to present <SFSafariViewController: 0x136810600> whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by UnateD** [myTargetSDK/mytarget-ios#9]
Добрый день. SDK используется в связке с MoPub для медиации. Метод register для регистрации кликабельных областей задается до момента, когда появится на ViewController'е, где отобразится реклама, в связи с чем в register попадает ссылка на ViewController родительский. При клике на UIView срабатывает попытка показать SFSafariViewController и, разумеется, этого не происходит. Имеется ли настройка для показа рекламы по клику с переходом в браузер, а не через SFSafariViewController ? К сожалению перенос register в иное место не представляется возможным

**Comment by lostillusion** [comment]
Добрый день. 
Конкретно для медиации в Mopub вы можете в MTRGMopubNativeAdAdapter.m на строке 82 передать нам nil в качестве контроллера, версия сдк должна быть 5.4.2 и выше.

**Comment by UnateD** [comment]
адаптер используется кастомный, реализованный по инструкции от mopub, в связи с чем решение не поможет, к сожалению

**Comment by lostillusion** [comment]
какой у вас номер слота?

**Comment by UnateD** [comment]
К сожалению в открытом доступе опубликовать не имею возможности. Я могу управлять вариантом перехода через настройку слота?

**Comment by lostillusion** [comment]
Вы - нет, мы - да. Тогда напишите сюда - sdk_mytarget@corp.my.com
